# Example minimal config
device:
  layer: rpizero2w   # Hardware target (e.g., cm5, rpi4, rpi5)
  hostname: campervan-computer

image:
  layer: embedded-svelte-static
  rootfs_type: ext4
  name: campervan-computer-os
  compression: zstd

layer:
  custom:
    - base-packages