#!/bin/sh

# Enable the overlay filesystem
sed -i "$1/boot/firmware/cmdline.txt" -e "s/^/overlayroot=tmpfs /"

# (Optional) Enable boot partition write-protection
sed -i "$1/etc/fstab" -e "s#\(.*/boot/firmware.*\)defaults\(.*\)#\1defaults,ro\2#"